version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    container_name: db_stats_container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  stats-server:
    build:
      context: ewm-stats-service/server
      dockerfile: Dockerfile
    image: stats-server-image
    container_name: stats_server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

    #ewm-service:
    #  ports:
    #    - "8080:8080"

    #ewm-db:
    #  image: postgres:15-alpine